# Generated by Django 5.1.6 on 2025-06-04 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classfee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classfee',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='class_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='fees.classfee'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='users.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'academic_year')},
        ),
        migrations.AddField(
            model_name='classfee',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='fees.term'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'class_fee')},
        ),
        migrations.AlterUniqueTogether(
            name='classfee',
            unique_together={('classroom', 'fee_category', 'term')},
        ),
    ]
