# Generated by Django 5.1.6 on 2025-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_storage', models.CharField(choices=[('local', 'Local File System'), ('backblaze_b2', 'Backblaze B2 Cloud Storage'), ('aws_s3', 'Amazon S3'), ('custom', 'Custom Storage Backend')], default='local', help_text='Currently active storage backend', max_length=20)),
                ('cloud_access_key', models.CharField(blank=True, help_text='Access key for cloud storage (B2 Application Key ID / AWS Access Key)', max_length=200)),
                ('cloud_secret_key', models.CharField(blank=True, help_text='Secret key for cloud storage (B2 Application Key / AWS Secret Key)', max_length=200)),
                ('cloud_bucket_name', models.CharField(blank=True, help_text='Bucket name for cloud storage', max_length=100)),
                ('cloud_region', models.CharField(blank=True, default='us-west-000', help_text='Region for cloud storage', max_length=50)),
                ('cloud_endpoint_url', models.URLField(blank=True, help_text='Custom endpoint URL (for B2 or S3-compatible services)')),
                ('cloud_custom_domain', models.CharField(blank=True, help_text='Custom domain for serving files (optional)', max_length=200)),
                ('auto_migrate_new_files', models.BooleanField(default=False, help_text='Automatically migrate new uploads to active storage')),
                ('last_migration_date', models.DateTimeField(blank=True, help_text='Last time files were migrated between storages', null=True)),
                ('migration_in_progress', models.BooleanField(default=False, help_text='Whether a migration is currently in progress')),
                ('local_files_count', models.IntegerField(default=0, help_text='Number of files in local storage')),
                ('cloud_files_count', models.IntegerField(default=0, help_text='Number of files in cloud storage')),
                ('total_storage_size_mb', models.FloatField(default=0.0, help_text='Total storage size in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Settings',
                'verbose_name_plural': 'Storage Settings',
            },
        ),
    ]
