# Generated by Django 5.1.6 on 2025-06-04 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentweightconfiguration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_weight_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.classsubject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.classsubject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_grading_scales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradethreshold',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='assignments.gradingscale'),
        ),
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='users.student'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='users.student'),
        ),
        migrations.AddField(
            model_name='reportcardsubjectgrade',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.reportcard'),
        ),
        migrations.AddField(
            model_name='reportcardsubjectgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='assignments.choice'),
        ),
        migrations.AddField(
            model_name='studentquizchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_choices', to='assignments.choice'),
        ),
        migrations.AddField(
            model_name='studentquizanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='assignments.studentquizchoice'),
        ),
        migrations.AddField(
            model_name='studentquizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_quiz_questions', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='studentquizchoice',
            name='student_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.studentquizquestion'),
        ),
        migrations.AddField(
            model_name='studentquizanswer',
            name='student_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.studentquizquestion'),
        ),
        migrations.AddField(
            model_name='studentquizversion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_versions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='studentquizversion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_versions', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentquizquestion',
            name='quiz_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.studentquizversion'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.studentsubmission'),
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='assignments.studentsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='gradethreshold',
            unique_together={('scale', 'letter_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'assignment', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'term', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcardsubjectgrade',
            unique_together={('report_card', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentquizchoice',
            unique_together={('student_question', 'choice')},
        ),
        migrations.AlterUniqueTogether(
            name='studentquizversion',
            unique_together={('student', 'assignment', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentquizquestion',
            unique_together={('quiz_version', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together={('student', 'assignment')},
        ),
    ]
